apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: jenkins-operator
  name: jenkins-operator
spec:
  ports:
  - name: metrics
    port: 8080
  selector:
    name: jenkins-operator
status:
  loadBalancer: {}
